### PR TITLE
Adds ERPDrobe for when we port shuttles and all. Also adds flavor text book.

### PR DESCRIPTION
**Pull request by bruhmogus**
cant be bothered to write a real description this time, it just adds the evil vending machine for the sake of compatibility when we port shuttles since its mapped three times iirc, and also adds a book that i... forgot to add to the vending list. god damn it.

### CODE REVIEW

**Comment by bruhmogus** [comment]
i will be deleting this branch the nanosecond it's merged, i fucked up and cloned this instead of my actual on jod fork

**Review by TheDoctor1977 — COMMENTED** [review]
i am hesitant to authorize merging this because we need to start thinking about the image we are projecting as a server
please consult with the rest of the admin team about readding this; the shuttle can very easily do without (it was one, the NTPD containment ship) and they're all probably going to be remapped from scratch anyway

**Comment by bruhmogus** [comment]
> i am hesitant to authorize merging this because we need to start thinking about the image we are projecting as a server please consult with the rest of the admin team about readding this; the shuttle can very easily do without (it was one, the NTPD containment ship) and they're all probably going to be remapped from scratch anyway

understandable, however it's merged to the ntpd containment ship, gulos zombie survival map, and i believe one of the stations?

**Comment by Erisfiregamer1** [comment]
Denied; as Doctor said we REALLY need to think about our image we're projecting and this jeporadizes that WAYYYYY too much. Feel free to PR with just the book.

I'll add a migration to null it out for mapping.

**Pull request closed without merging**
