### PR TITLE
Syndicate clothing support for the open world game mode.

### PR DESCRIPTION
**Pull request by Guloveos**
## About the PR

Added Syndicate clothing for the open world game mode, figured I would push the uniforms for fun.

## Why / Balance

This adds support for the open world game mode new roles.

## Media

To go threw and get photos of all the clothing would take WAY to long. Most of the uniforms are just slight changes to the arms.

## Requirements

- [ X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Guloveos** [comment]
Hold up why the hell does it say -2000?

**Comment by bruhmogus** [comment]
what did bro do 💀

**Comment by TheDoctor1977** [comment]
> Hold up why the hell does it say -2000?

everything in these folders appears to have been removed 
IMG_8519

**Comment by bruhmogus** [comment]
is this fikssed yet

**Comment by TheDoctor1977** [comment]
as resident Git Guy eris earns the prize of figuring this out

**Comment by GroggleG** [comment]
rerun the build test, looks like a fluke.

**Comment by Erisfiregamer1** [comment]
PR is based on prebase code, please remake on new code.

No, this isn't me dodging fixing the deletion of a ton of sprites.

**Pull request closed without merging**
